### ISSUE TITLE
PJSIP as Dynamic Library for use in a 'swift' Cocoapod

### ISSUE THREAD

**Issue by mohpor** [VoIPGRID/Vialer-pjsip-iOS#1]
I have been reading and following Cocoapod's repo issues related to adding static libraries as dependency to dynamic frameworks. Looks like it's intentional and they have legit reasons for having this check. Therefore, this pod should solve this problem with a workaround suitable for both Objective-C and Swift projects. `use_frameworks!` is a crucial part of Swift projects and without that, projects with swift pod dependencies will get errors. So, to sum it up, any ideas?

For more discussion on this dilemma: [CocoaPods/#3839](https://github.com/CocoaPods/CocoaPods/issues/3839)

**Comment by bobvoorneveld** [comment]
We are working hard on a solution for this, because we really would like it to use in swift projects. So far, after a couple of days of compiling, testing and pulling our hairs out, we haven't found a solution on how to make sure this pod can be included in an swift project. We'll keep you updated.

**Comment by mohpor** [comment]
Have you tried this: [Prevent Transitive Dependency Errors in Swift Project with Vendored Frameworks](https://github.com/CocoaPods/CocoaPods/issues/3289).
I'm not sure that this would apply to our situation but it looks like a working solution for now.

**Comment by r3b3l** [comment]
As far as I have figured out, there is no real work around other than to build PJSIP Dynamically which we have been unable to to so far. [See our PJSIP mailing list post](http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2016-August/019448.html)

**Comment by mohpor** [comment]
That's sad news. But I'm sure we are able to solve it. Just need some team effort.

**Comment by Harold-D** [comment]
I have fixed the error about classes and frameworks not being found as described in the mailing PJSIP mailing list post mentioned in my previous message.

I have found a partial sollution. When compiling PJSIP with the `--enable-shared` option, most of the lib's created by the build process are build correctly as dylib and for the correct architecture (e.g. arm64).
However, some libs are compile for the wrong architecture, in this case
x86_64 instead of arm64
libg7221codec.dylib is architecture: x86_64
libgsmcodec.dylib is architecture: x86_64
libilbccodec.dylib is architecture: x86_64
libresample.dylib is architecture: x86_64
libyuv.dylib is architecture: x86_64

Whereas these are correct:
libpjsip.dylib is architecture: arm64
libpjsua.dylib is architecture: arm64
libpjsua2.dylib is architecture: arm64

```
+ ./configure-iphone --enable-shared
+ make dep
+ make clean
```
al complete correctly but
`+ make`
generates these warnings:
```
ld: warning: -undefined dynamic_lookup is deprecated on iOS
ld: warning: -flat_namespace is deprecated on iOS
```

and a lot of warnings looking like this:
`ld: warning: ignoring file output/libilbccodec-arm64-apple-darwin_ios/iLBC_decode.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): output/libilbccodec-arm64-apple-darwin_ios/iLBC_decode.o`
`ld: warning: ignoring file output/libg7221codec-arm64-apple-darwin_ios/common/common.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): output/libg7221codec-arm64-apple-darwin_ios/common/common.o`

and:
`ld: warning: ignoring file /pjsip/src/third_party/lib/libg7221codec.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /pjsip/src/third_party/lib/libg7221codec.dylib`

What could be the reason that some lib's are compiled for the correct architecture and some are not? How would I be able to fix this?


For background information, the environment variables as printed by
```
configure-iphone: DEVPATH is not specified, using /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
configure-iphone: IPHONESDK is not specified, choosing iPhoneOS9.3.sdk
configure-iphone: CC is not specified, choosing /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
configure-iphone: CXX is not specified, using /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
```

configure-iphone: calling ./aconfigure with env vars:
```
CC = /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX = /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
SDKPATH = /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk
CFLAGS = -miphoneos-version-min=9.0 -DPJ_SDK_NAME="\"iPhoneOS9.3.sdk\"" -arch arm64 -isysroot /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk
LDFLAGS = -O2 -arch arm64 -isysroot /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -framework AudioToolbox -framework Foundation
AR = /Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -o
RANLIB = echo ranlib
ARCH = arm64
```
[PJSIP mailing list post](http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2016-August/019492.html)

**Comment by cybrox** [comment]
Has there been any progress on resolving this issue?
I would love to implement the `VialerSIPLib` (and therefore this pod as well) in a project that I am currently forced to convert to Swift. However, due to using quite a lot of swift pods, I am forced to use `use_frameworks!` which leaves me with the issue described here.

Status updates or even workarounds would be greatly appreciated.

**Comment by bobvoorneveld** [comment]
Hi @cybrox, we haven't had any success. We would really have the lib in swift, because we're moving to swift with our projects. But compiling the lib in the correct way is still impossible for us. If you have any tips or know someone who can help, please let us know.

**Comment by cybrox** [comment]
Hi @bobvoorneveld, thanks for the quick reply!
I don't know how much you tried and if this helps, but here's what I did so far:

- I installed [this pod](https://github.com/chebur/pjsip) for getting a compiled version of pjsip. (Also tried manually compiling, which worked as well but I decided the pod is a tidy solution.)

- With compiled pjsip ready, I added a custom `pjmedia/module.map` to my project:
```
module pjmedia {
  <other submodules>

  module pjsua {
    header "/Users/sgehring/development/.../Pods/pjsip/build/pjproject/src/pjsip/include/pjsua.h"
    export *  
  }

  module pjsip {
    header "/Users/sgehring/development/.../Pods/pjsip/build/pjproject/src/pjsip/include/pjsip.h"
    export *  
  }
}
```

- With that, I can use static library, such as the compiled pjsip as part of the dynamic framework. (`Import pjmedia.pjsua`)

I have not yet found a proper way to build the vialer library on top of that but as far I know, cocoapods supports modulemaps, so maybe there is a way to wrap the library like that. Just wanted to share what I figured out so far, maybe it is of use for you.

**Comment by bkr1989** [comment]
Hi @bobvoorneveld  ... is there a Pjsip pod for swift project available now..

**Comment by redmerloen** [comment]
@bobvoorneveld is not working on this project anymore. And No there is not a dynamic library available. For our own project it is not yet a priority so this also has no priority

**Comment by bkr1989** [comment]
@redmerloen thanks for ur reply...can we get the same results with vialerSIPLib ?

**Comment by skv13391** [comment]
Undefined symbols for architecture x86_64:
  "_pjsua_conf_remove_port", referenced from:
      -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
      -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
  "_pjmedia_tonegen_create2", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjmedia_tonegen_play", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_enum_transports", referenced from:
      -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_set_snd_dev2", referenced from:
      -[VSLAudioController activateAudioSession] in libVialerSIPLib.a(VSLAudioController.o)
  "_pjsua_enum_codecs", referenced from:
      -[VSLEndpoint updateCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
I got this issue when integrate this framework.

**Comment by maxkomarychev** [comment]
as of cocoapods 1.5 it is possible to build swift code into static libs http://blog.cocoapods.org/CocoaPods-1.5.0/ so `use_frameworks!` isn't required anymore when working with swifth

**Comment by redmerloen** [comment]
Yes I have tested it and removing `use_frameworks!` compiles the code fine. Could people check this in their Swift only projects to see if removing `use_frameworks!` works?

**Comment by doniyansyahputra** [comment]
![screen shot 2018-12-05 at 10 08 40](https://user-images.githubusercontent.com/44077664/49487601-c7b21900-f875-11e8-8a05-0f6eccaed0c9.png)

why error?
